//
//  CountryModel.swift
//  SwiftDataTutorial
//
//

import Foundation
import SwiftData

@Model
class CountryModel{
    var id = UUID()
    var name: String
    var code: String
    
    @Relationship(deleteRule: .cascade, inverse: \CityModel.country)
    var cities: [CityModel]?
    
    init(name: String, code: String) {
        self.name = name
        self.code = code
    }
    
    static func getRandomCountry() -> CountryModel{
        let countries = [
            CountryModel(name: "Afghanistan", code: "AF"),
            CountryModel(name: "Albania", code: "AL"),
            CountryModel(name: "Algeria", code: "DZ"),
            CountryModel(name: "American Samoa", code: "AS"),
            CountryModel(name: "Andorra", code: "AD"),
            CountryModel(name: "Angola", code: "AO"),
            CountryModel(name: "Anguilla", code: "AI"),
            CountryModel(name: "Antarctica", code: "AQ"),
            CountryModel(name: "Antigua and Barbuda", code: "AG"),
            CountryModel(name: "Argentina", code: "AR"),
            CountryModel(name: "Armenia", code: "AM"),
            CountryModel(name: "Aruba", code: "AW"),
            CountryModel(name: "Asia/Pacific Region", code: "AP"),
            CountryModel(name: "Australia", code: "AU"),
            CountryModel(name: "Austria", code: "AT"),
            CountryModel(name: "Azerbaijan", code: "AZ"),
            CountryModel(name: "Bahamas", code: "BS"),
            CountryModel(name: "Bahrain", code: "BH"),
            CountryModel(name: "Bangladesh", code: "BD"),
            CountryModel(name: "Barbados", code: "BB"),
            CountryModel(name: "Belarus", code: "BY"),
            CountryModel(name: "Belgium", code: "BE"),
            CountryModel(name: "Belize", code: "BZ"),
            CountryModel(name: "Benin", code: "BJ"),
            CountryModel(name: "Bermuda", code: "BM"),
            CountryModel(name: "Bhutan", code: "BT"),
            CountryModel(name: "Bolivia", code: "BO"),
            CountryModel(name: "Bonaire, Sint Eustatius and Saba", code: "BQ"),
            CountryModel(name: "Bosnia and Herzegovina", code: "BA"),
            CountryModel(name: "Botswana", code: "BW"),
            CountryModel(name: "Bouvet Island", code: "BV"),
            CountryModel(name: "Brazil", code: "BR"),
            CountryModel(name: "British Indian Ocean Territory", code: "IO"),
            CountryModel(name: "Brunei Darussalam", code: "BN"),
            CountryModel(name: "Bulgaria", code: "BG"),
            CountryModel(name: "Burkina Faso", code: "BF"),
            CountryModel(name: "Burundi", code: "BI"),
            CountryModel(name: "Cambodia", code: "KH"),
            CountryModel(name: "Cameroon", code: "CM"),
            CountryModel(name: "Canada", code: "CA"),
            CountryModel(name: "Cape Verde", code: "CV"),
            CountryModel(name: "Cayman Islands", code: "KY"),
            CountryModel(name: "Central African Republic", code: "CF"),
            CountryModel(name: "Chad", code: "TD"),
            CountryModel(name: "Chile", code: "CL"),
            CountryModel(name: "China", code: "CN"),
            CountryModel(name: "Christmas Island", code: "CX"),
            CountryModel(name: "Cocos (Keeling) Islands", code: "CC"),
            CountryModel(name: "Colombia", code: "CO"),
            CountryModel(name: "Comoros", code: "KM"),
            CountryModel(name: "Congo", code: "CG"),
            CountryModel(name: "Congo, The Democratic Republic of the", code: "CD"),
            CountryModel(name: "Cook Islands", code: "CK"),
            CountryModel(name: "Costa Rica", code: "CR"),
            CountryModel(name: "Croatia", code: "HR"),
            CountryModel(name: "Cuba", code: "CU"),
            CountryModel(name: "Curaçao", code: "CW"),
            CountryModel(name: "Cyprus", code: "CY"),
            CountryModel(name: "Czech Republic", code: "CZ"),
            CountryModel(name: "Côte d'Ivoire", code: "CI"),
            CountryModel(name: "Denmark", code: "DK"),
            CountryModel(name: "Djibouti", code: "DJ"),
            CountryModel(name: "Dominica", code: "DM"),
            CountryModel(name: "Dominican Republic", code: "DO"),
            CountryModel(name: "Ecuador", code: "EC"),
            CountryModel(name: "Egypt", code: "EG"),
            CountryModel(name: "El Salvador", code: "SV"),
            CountryModel(name: "Equatorial Guinea", code: "GQ"),
            CountryModel(name: "Eritrea", code: "ER"),
            CountryModel(name: "Estonia", code: "EE"),
            CountryModel(name: "Ethiopia", code: "ET"),
            CountryModel(name: "Falkland Islands (Malvinas)", code: "FK"),
            CountryModel(name: "Faroe Islands", code: "FO"),
            CountryModel(name: "Fiji", code: "FJ"),
            CountryModel(name: "Finland", code: "FI"),
            CountryModel(name: "France", code: "FR"),
            CountryModel(name: "French Guiana", code: "GF"),
            CountryModel(name: "French Polynesia", code: "PF"),
            CountryModel(name: "French Southern Territories", code: "TF"),
            CountryModel(name: "Gabon", code: "GA"),
            CountryModel(name: "Gambia", code: "GM"),
            CountryModel(name: "Georgia", code: "GE"),
            CountryModel(name: "Germany", code: "DE"),
            CountryModel(name: "Ghana", code: "GH"),
            CountryModel(name: "Gibraltar", code: "GI"),
            CountryModel(name: "Greece", code: "GR"),
            CountryModel(name: "Greenland", code: "GL"),
            CountryModel(name: "Grenada", code: "GD"),
            CountryModel(name: "Guadeloupe", code: "GP"),
            CountryModel(name: "Guam", code: "GU"),
            CountryModel(name: "Guatemala", code: "GT"),
            CountryModel(name: "Guernsey", code: "GG"),
            CountryModel(name: "Guinea", code: "GN"),
            CountryModel(name: "Guinea-Bissau", code: "GW"),
            CountryModel(name: "Guyana", code: "GY"),
            CountryModel(name: "Haiti", code: "HT"),
            CountryModel(name: "Heard Island and Mcdonald Islands", code: "HM"),
            CountryModel(name: "Holy See (Vatican City State)", code: "VA"),
            CountryModel(name: "Honduras", code: "HN"),
            CountryModel(name: "Hong Kong", code: "HK"),
            CountryModel(name: "Hungary", code: "HU"),
            CountryModel(name: "Iceland", code: "IS"),
            CountryModel(name: "India", code: "IN"),
            CountryModel(name: "Indonesia", code: "ID"),
            CountryModel(name: "Iran, Islamic Republic Of", code: "IR"),
            CountryModel(name: "Iraq", code: "IQ"),
            CountryModel(name: "Ireland", code: "IE"),
            CountryModel(name: "Isle of Man", code: "IM"),
            CountryModel(name: "Israel", code: "IL"),
            CountryModel(name: "Italy", code: "IT"),
            CountryModel(name: "Jamaica", code: "JM"),
            CountryModel(name: "Japan", code: "JP"),
            CountryModel(name: "Jersey", code: "JE"),
            CountryModel(name: "Jordan", code: "JO"),
            CountryModel(name: "Kazakhstan", code: "KZ"),
            CountryModel(name: "Kenya", code: "KE"),
            CountryModel(name: "Kiribati", code: "KI"),
            CountryModel(name: "Korea, Republic of", code: "KR"),
            CountryModel(name: "Kuwait", code: "KW"),
            CountryModel(name: "Kyrgyzstan", code: "KG"),
            CountryModel(name: "Laos", code: "LA"),
            CountryModel(name: "Latvia", code: "LV"),
            CountryModel(name: "Lebanon", code: "LB"),
            CountryModel(name: "Lesotho", code: "LS"),
            CountryModel(name: "Liberia", code: "LR"),
            CountryModel(name: "Libyan Arab Jamahiriya", code: "LY"),
            CountryModel(name: "Liechtenstein", code: "LI"),
            CountryModel(name: "Lithuania", code: "LT"),
            CountryModel(name: "Luxembourg", code: "LU"),
            CountryModel(name: "Macao", code: "MO"),
            CountryModel(name: "Madagascar", code: "MG"),
            CountryModel(name: "Malawi", code: "MW"),
            CountryModel(name: "Malaysia", code: "MY"),
            CountryModel(name: "Maldives", code: "MV"),
            CountryModel(name: "Mali", code: "ML"),
            CountryModel(name: "Malta", code: "MT"),
            CountryModel(name: "Marshall Islands", code: "MH"),
            CountryModel(name: "Martinique", code: "MQ"),
            CountryModel(name: "Mauritania", code: "MR"),
            CountryModel(name: "Mauritius", code: "MU"),
            CountryModel(name: "Mayotte", code: "YT"),
            CountryModel(name: "Mexico", code: "MX"),
            CountryModel(name: "Micronesia, Federated States of", code: "FM"),
            CountryModel(name: "Moldova, Republic of", code: "MD"),
            CountryModel(name: "Monaco", code: "MC"),
            CountryModel(name: "Mongolia", code: "MN"),
            CountryModel(name: "Montenegro", code: "ME"),
            CountryModel(name: "Montserrat", code: "MS"),
            CountryModel(name: "Morocco", code: "MA"),
            CountryModel(name: "Mozambique", code: "MZ"),
            CountryModel(name: "Myanmar", code: "MM"),
            CountryModel(name: "Namibia", code: "NA"),
            CountryModel(name: "Nauru", code: "NR"),
            CountryModel(name: "Nepal", code: "NP"),
            CountryModel(name: "Netherlands", code: "NL"),
            CountryModel(name: "Netherlands Antilles", code: "AN"),
            CountryModel(name: "New Caledonia", code: "NC"),
            CountryModel(name: "New Zealand", code: "NZ"),
            CountryModel(name: "Nicaragua", code: "NI"),
            CountryModel(name: "Niger", code: "NE"),
            CountryModel(name: "Nigeria", code: "NG"),
            CountryModel(name: "Niue", code: "NU"),
            CountryModel(name: "Norfolk Island", code: "NF"),
            CountryModel(name: "North Korea", code: "KP"),
            CountryModel(name: "North Macedonia", code: "MK"),
            CountryModel(name: "Northern Mariana Islands", code: "MP"),
            CountryModel(name: "Norway", code: "NO"),
            CountryModel(name: "Oman", code: "OM"),
            CountryModel(name: "Pakistan", code: "PK"),
            CountryModel(name: "Palau", code: "PW"),
            CountryModel(name: "Palestinian Territory, Occupied", code: "PS"),
            CountryModel(name: "Panama", code: "PA"),
            CountryModel(name: "Papua New Guinea", code: "PG"),
            CountryModel(name: "Paraguay", code: "PY"),
            CountryModel(name: "Peru", code: "PE"),
            CountryModel(name: "Philippines", code: "PH"),
            CountryModel(name: "Pitcairn Islands", code: "PN"),
            CountryModel(name: "Poland", code: "PL"),
            CountryModel(name: "Portugal", code: "PT"),
            CountryModel(name: "Puerto Rico", code: "PR"),
            CountryModel(name: "Qatar", code: "QA"),
            CountryModel(name: "Reunion", code: "RE"),
            CountryModel(name: "Romania", code: "RO"),
            CountryModel(name: "Russian Federation", code: "RU"),
            CountryModel(name: "Rwanda", code: "RW"),
            CountryModel(name: "Saint Barthélemy", code: "BL"),
            CountryModel(name: "Saint Helena", code: "SH"),
            CountryModel(name: "Saint Kitts and Nevis", code: "KN"),
            CountryModel(name: "Saint Lucia", code: "LC"),
            CountryModel(name: "Saint Martin", code: "MF"),
            CountryModel(name: "Saint Martin", code: "MF"),
            CountryModel(name: "Saint Pierre and Miquelon", code: "PM"),
            CountryModel(name: "Saint Vincent and the Grenadines", code: "VC"),
            CountryModel(name: "Samoa", code: "WS"),
            CountryModel(name: "San Marino", code: "SM"),
            CountryModel(name: "Sao Tome and Principe", code: "ST"),
            CountryModel(name: "Saudi Arabia", code: "SA"),
            CountryModel(name: "Senegal", code: "SN"),
            CountryModel(name: "Serbia", code: "RS"),
            CountryModel(name: "Serbia and Montenegro", code: "CS"),
            CountryModel(name: "Seychelles", code: "SC"),
            CountryModel(name: "Sierra Leone", code: "SL"),
            CountryModel(name: "Singapore", code: "SG"),
            CountryModel(name: "Sint Maarten", code: "SX"),
            CountryModel(name: "Slovakia", code: "SK"),
            CountryModel(name: "Slovenia", code: "SI"),
            CountryModel(name: "Solomon Islands", code: "SB"),
            CountryModel(name: "Somalia", code: "SO"),
            CountryModel(name: "South Africa", code: "ZA"),
            CountryModel(name: "South Georgia and the South Sandwich Islands", code: "GS"),
            CountryModel(name: "South Sudan", code: "SS"),
            CountryModel(name: "Spain", code: "ES"),
            CountryModel(name: "Sri Lanka", code: "LK"),
            CountryModel(name: "Sudan", code: "SD"),
            CountryModel(name: "Suriname", code: "SR"),
            CountryModel(name: "Svalbard and Jan Mayen", code: "SJ"),
            CountryModel(name: "Swaziland", code: "SZ"),
            CountryModel(name: "Sweden", code: "SE"),
            CountryModel(name: "Switzerland", code: "CH"),
            CountryModel(name: "Syrian Arab Republic", code: "SY"),
            CountryModel(name: "Taiwan", code: "TW"),
            CountryModel(name: "Tajikistan", code: "TJ"),
            CountryModel(name: "Tanzania, United Republic of", code: "TZ"),
            CountryModel(name: "Thailand", code: "TH"),
            CountryModel(name: "Timor-Leste", code: "TL"),
            CountryModel(name: "Togo", code: "TG"),
            CountryModel(name: "Tokelau", code: "TK"),
            CountryModel(name: "Tonga", code: "TO"),
            CountryModel(name: "Trinidad and Tobago", code: "TT"),
            CountryModel(name: "Tunisia", code: "TN"),
            CountryModel(name: "Turkey", code: "TR"),
            CountryModel(name: "Turkmenistan", code: "TM"),
            CountryModel(name: "Turks and Caicos Islands", code: "TC"),
            CountryModel(name: "Tuvalu", code: "TV"),
            CountryModel(name: "Uganda", code: "UG"),
            CountryModel(name: "Ukraine", code: "UA"),
            CountryModel(name: "United Arab Emirates", code: "AE"),
            CountryModel(name: "United Kingdom", code: "GB"),
            CountryModel(name: "United States", code: "US"),
            CountryModel(name: "United States Minor Outlying Islands", code: "UM"),
            CountryModel(name: "Uruguay", code: "UY"),
            CountryModel(name: "Uzbekistan", code: "UZ"),
            CountryModel(name: "Vanuatu", code: "VU"),
            CountryModel(name: "Venezuela", code: "VE"),
            CountryModel(name: "Vietnam", code: "VN"),
            CountryModel(name: "Virgin Islands, British", code: "VG"),
            CountryModel(name: "Virgin Islands, U.S.", code: "VI"),
            CountryModel(name: "Wallis and Futuna", code: "WF"),
            CountryModel(name: "Western Sahara", code: "EH"),
            CountryModel(name: "Yemen", code: "YE"),
            CountryModel(name: "Zambia", code: "ZM"),
            CountryModel(name: "Zimbabwe", code: "ZW"),
            CountryModel(name: "Åland Islands", code: "AX"),
        ]
        
        return countries.randomElement()!
    }
}
